# Generated by Django 5.2 on 2025-04-29 09:37

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', max_length=255, null=True, upload_to=home.models.avatar_upload_to),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Sale price in PokéCoins', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.ForeignKey(help_text='Pokémon being sold', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='home.pokemon')),
                ('seller', models.ForeignKey(help_text='Who is selling this Pokémon', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='home.profile')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
