# Generated by Django 5.2 on 2025-04-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_id', models.PositiveIntegerField(help_text='ID from PokéAPI', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sprite', models.URLField(blank=True, null=True)),
                ('types', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('health', models.IntegerField(default=0)),
            ],
        ),
    ]
