# Generated by Django 5.2 on 2025-04-29 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_avatar_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Which Profile owns this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to='home.profile'),
        ),
    ]
