# Generated by Django 5.2 on 2025-04-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pokemon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Which Profile owns this card', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='home.profile'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='poke_id',
            field=models.PositiveIntegerField(help_text='ID from PokéAPI'),
        ),
    ]
