# Generated by Django 5.2 on 2025-04-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collection',
            field=models.ManyToManyField(blank=True, help_text='All Pokémon this user owns', related_name='owners', to='home.pokemon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='starter_pokemon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
