# Generated by Django 5.2 on 2025-04-29 06:18

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', max_length=255, null=True, upload_to=home.models.avatar_upload_to),
        ),
    ]
