# Generated by Django 5.2 on 2025-04-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_collection_alter_profile_starter_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starter_pokemon',
        ),
    ]
