# Generated by Django 5.1.5 on 2025-04-29 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_currency_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_reward',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
