# Generated by Django 5.1.5 on 2025-04-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pokemon_attack_pokemon_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_approved_by_admin',
            field=models.BooleanField(default=True),
        ),
    ]
